version: '3.9'

services:
  backend-app:
    image: backend-app:0.0.1
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: backdb-app
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - backdb-app

  backdb-app:
    image: mysql:8.0.26
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: fullstackdb
      MYSQL_ROOT_PASSWORD: root